libbase-$(CONFIG_SOC_WITH_ETHMAC) += div64.o
libbase-$(CONFIG_SOC_WITH_ETHMAC) += progress.o
libbase-$(CONFIG_SOC_WITH_ETHMAC) += system.o

libliteeth-$(CONFIG_SOC_WITH_ETHMAC) += mdio.o
libliteeth-$(CONFIG_SOC_WITH_ETHMAC) += tftp.o
libliteeth-$(CONFIG_SOC_WITH_ETHMAC) += udp.o

crt-$(CONFIG_SOC_WITH_ETHMAC) += divsi3.o
crt-$(CONFIG_SOC_WITH_ETHMAC) += modsi3.o
crt-$(CONFIG_SOC_WITH_ETHMAC) += muldi3.o
